;**************************************************************************
; AUTOCAD: PABLO ROSALES Y SANTERI SUITIALA
; PAREJA 9  
;**************************************************************************


DATOS SEGMENT
	MENSAJE1	DB	"TEST$"
	MENSAJE2	DB	54,31,53,54
DATOS ENDS


PILA SEGMENT STACK "STACK"
	DB	50h	DUP(0)
PILA ENDS


CODE SEGMENT
	ASSUME CS:CODE, DS:DATOS, SS:PILA

	INICIO PROC NEAR
		MOV AX, DATOS
		MOV DS, AX
		MOV AX, PILA
		MOV SS, AX
		MOV SP, 64
		
		CALL TESTCODIFICACION
		CALL TESTDECODIFICACION		
		
		; fin del programa
		MOV AX, 4C00H
		INT 21H
	INICIO ENDP

	TESTCODIFICACION PROC NEAR
		PUSH AX DX
		MOV DX, OFFSET MENSAJE1
		MOV AH, 10
		INT 57H
		POP DX AX
		RET
	TESTCODIFICACION ENDP
		
	TESTDECODIFICACION PROC NEAR
		PUSH AX DX
		MOV DX, OFFSET MENSAJE2
		MOV AH, 11
		INT 57H
		POP DX AX
		RET
	TESTDECODIFICACION ENDP

CODE ENDS

END INICIO
